---

- name: Generating master key for ec2-user
  user: "name=ec2-user generate_ssh_key=yes"
  delegate_to: "{{master_elastic_ip['public_ip']}}"
  remote_user: "ec2-user"

- name: register master pub key
  shell: "cat ~/.ssh/id_rsa.pub"
  delegate_to: "{{master_elastic_ip['public_ip']}}"
  remote_user: "ec2-user"
  register: "ec2_rsa_pub"

- name: install master pub key on nodes
  authorized_key: user="ec2-user" key="{{ ec2_rsa_pub.stdout }}"
  delegate_to: "{{item}}"
  remote_user: "ec2-user"
  with_items:
   - "{{ec2_node1['tagged_instances'][0]['public_ip']}}"
   - "{{ec2_node2['tagged_instances'][0]['public_ip']}}"
