---

# access for master
- name: Generating master key for ec2-user
  user: "name={{amazon_user}} generate_ssh_key=yes"
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: register master pub key
  shell: "cat ~/.ssh/id_rsa.pub"
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"
  register: "master_rsa_pub"

- name: install master pub key on bastion
  authorized_key: user="{{amazon_user}}" key="{{ master_rsa_pub.stdout }}"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{bastion_public_ip}}"

- name: install master pub key on nodes
  authorized_key: user="{{amazon_user}}" key="{{ master_rsa_pub.stdout }}"
  delegate_to: "{{item.public_ip}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{nodes_ip}}"

# access for bastion
- name: Generating bastion key for ec2-user
  user: "name={{amazon_user}} generate_ssh_key=yes"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: register bastion pub key
  shell: "cat ~/.ssh/id_rsa.pub"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  register: "bastion_rsa_pub"

- name: install bastion pub key on master
  authorized_key: user="{{amazon_user}}" key="{{ bastion_rsa_pub.stdout }}"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{master_public_ip}}"

- name: install bastion pub key on nodes
  authorized_key: user="{{amazon_user}}" key="{{ bastion_rsa_pub.stdout }}"
  delegate_to: "{{item.public_ip}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{nodes_ip}}"
