---

- name: Install Openshift

  hosts: local

  vars_files:
    - vars/aws-credentials
    - vars/aws-config.yml

    vars:
      state: 'present'

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"

  roles:
  - aws-setup-vpc

  post_tasks:
   - name: Confirmation message
     debug:
      msg: 'Finished'

