---

- name: Install Openshift

  hosts: local

  vars_files:
    - vars/aws-config.yml
    - vars/secrets-config.yml

  vars:
    state: 'present'

  roles:
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh
  - openshift-pre-reqs
  - openshift-install

  pre_tasks:
    - fail: msg="Variable '{{ item }}' is not defined or is empty"
      when: (deployment_type == 'openshift-enterprise') and ((item not in vars) or vars[item] == '')
      with_items: 
        - rhsm_username
        - rhsm_password
        - rhsm_pool

  post_tasks:
   - name: Confirmation message
     debug:
      msg: 'Finished, public master IP: {{master_public_ip}}'

