---
#############################################################
# Provision AWS infrastructure
#############################################################
- name: Create Infrastructure
  hosts: local

  vars_files:
    - vars/aws-config.yml
    - vars/secrets-config.yml

  vars:
    state: 'present'

  roles:
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh

  pre_tasks:
    - fail: msg="Variable '{{ item }}' is not defined or is empty"
      when: (deployment_type == 'openshift-enterprise') and ((item not in vars) or vars[item] == '')
      with_items: 
        - rhsm_username
        - rhsm_password
        - rhsm_pool

#############################################################
# Register and update virtual machines
#############################################################
- name: Setup VM hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

  tasks:
    - name: Add nodes to created_nodes group
      add_host:
        name={{ item.ip }}
        groups=created_vms
        instance_name={{ item.name }}
      with_items:
        - { name: 'master', ip: '{{master_public_ip}}' }
        - { name: 'node1', ip: '{{node1_public_ip}}' }
        - { name: 'node2', ip: '{{node2_public_ip}}' }  
        - { name: 'bastion', ip: '{{bastion_public_ip}}' }  

- name: Register and update virtual machines
  hosts: created_vms
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml
    - vars/secrets-config.yml

  vars:
    state: 'present'

  roles:    

  - {role: register-virtual-machines, when: deployment_type == 'openshift-enterprise'}
  - update-virtual-machines

#############################################################
# Openshift Prerequisites
#############################################################
- name: Setup Node hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

  tasks:
    - name: Add nodes to created_nodes group
      add_host:
        name={{ item.ip }}
        groups=created_nodes
        instance_name={{ item.name }}
      with_items:
        - { name: 'master', ip: '{{master_public_ip}}' }
        - { name: 'node1', ip: '{{node1_public_ip}}' }
        - { name: 'node2', ip: '{{node2_public_ip}}' }  

- name: OpenShift Prerequisites
  hosts: created_nodes
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:
  - openshift-pre-reqs

#############################################################
# Install Openshift
#############################################################
- name: Install OpenShift
  hosts: local

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:
  - openshift-install

  post_tasks:
   - name: Confirmation message
     debug:
      msg: 'Finished, public master IP: {{master_public_ip}}'