---

- name: Teardown Environment

  hosts: "local"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  post_tasks:
    - name: Completed
      debug:
        msg: 'Finished tearing down environment {{namespace}}'

  roles:
  - teardown-virtual-machines
  - teardown-security-groups
  - teardown-vpc
  - teardown-dns