---

- name: Provision VPC
  ec2_vpc_net:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    name: "{{namespace}}-vpc"
    state: "present"
    cidr_block: "{{ vpc_cidr }}"
    tags:
      mits4u: "{{namespace}}-vpc"
    region: "{{ region }}"

- name: Get VPC ID
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{namespace}}-vpc"

- name: VPC ID
  debug:
    var: vpc_facts['vpcs'][0]['id']


# - name: Provision gateway [access to internet]
#   ec2:
#      ec2_access_key: "{{ ec2_access_key }}"
#      ec2_secret_key: "{{ ec2_secret_key }}"
##        key_name: my_key
##        group: test
#      instance_type: t2.micro
#      image: "ami-b9353fdd"
#      region: "eu-central-1"
#      wait: true
#      exact_count: 1
#      count_tag:
#          Name: Demo
#      instance_tags:
#         Name: Demo
#   register: ec2
#
#
#
