---

- name: Provision VPC
  ec2_vpc_net:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    name: "{{namespace}}-vpc"
    cidr_block: "{{ vpc_cidr }}"
    tags:
      Name: "{{namespace}}-vpc"
      mits4u: "{{namespace}}-vpc"
    region: "{{ region }}"
    state: "present"
  register: vpc_facts

- name: print VPC ID
  debug:
    msg: "Created VPC with ID: {{vpc_facts['vpc']['id']}}"

- name: Provision internet gateway
  ec2_vpc_igw:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    region: "{{ region }}"
    state: "present"
  register: igw_facts

- name: print internet gateway ID
  debug:
    msg: "Created internet gateway with ID: {{igw_facts['gateway_id']}}"

- name: Provision subnet
  ec2_vpc_subnet:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    cidr: "{{subnet_cidr}}"
    tags:
      Name: "{{namespace}}-subnet"
      mits4u: "{{namespace}}-subnet"
    region: "{{ region }}"
    state: "present"
  register: subnet


# - name: Provision gateway [access to internet]
#   ec2:
#      ec2_access_key: "{{ ec2_access_key }}"
#      ec2_secret_key: "{{ ec2_secret_key }}"
##        key_name: my_key
##        group: test
#      instance_type: t2.micro
#      image: "ami-b9353fdd"
#      region: "eu-central-1"
#      wait: true
#      exact_count: 1
#      count_tag:
#          Name: Demo
#      instance_tags:
#         Name: Demo
#   register: ec2
#
#
#
