---
- name: Gather EC2 facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{namespace}}"
  register: ec2_facts

- name: Unregister VMs
  include: unregister-vm.yml public_ip={{ item.public_ip_address }}
  with_items: "{{ ec2_facts.instances }}"
  when: ((deployment_type == 'openshift-enterprise') and (item.state != 'terminated'))
  ignore_errors: yes

- name: Terminate EC2 VMs
  ec2:
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'