---
- name: Gather EC2 facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{namespace}}"
  register: ec2_facts

#- name: Debug
#  debug:
#    msg: "{{ item.id }}"
#  with_items: "{{ ec2_facts.instances }}"

- name: Terminate EC2 VMs
  ec2:
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"