---
#This security group allows intra-node communication on all ports with all protocols.
- name: create openshift-vpc
  ec2_group:
    name: "openshift-vpc"
    description: "Default security group that allows all instances in the VPC to talk to each other over any port and protocol."
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    region: "{{region}}"
    rules:
      - proto: "ALL"
        from_port: "ALL"
        to_port: "ALL"
    rules_egress:
      - proto: "ALL"
        from_port: "ALL"
        to_port: "ALL"

