
  region: "us-west-2"
  vpc_cidr: "10.0.0.0/16"
  subnet_cidr: "10.0.1.0/24"
  namespace: "openshift"
  dns_zone: "ose.local"
  aws_key_pair: "gnunn"
  amazon_user: "ec2-user"
  openshift_branch: "release-1.5"
  # ec2
  amisize: "t2.large"
  amiid: "ami-f05f5489"
  redhat_owner_id: "309956199498"
  amazon_owner_id: "137112412989"
  bastion_amisize: "t2.micro"
  volume_size: 50
  #DNS
  public_dns_zone: "ocplab.com"
