region: "us-west-2"
vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"
namespace: "openshift"
# dns_zone is private zone, created and deleted by scripts
dns_zone: "ose.local"
# Public DNS for cluster
public_dns_zone: "ocplab.com"
# Prefix for subdomain for apps, i.e. epps.ocplab.com
public_subdomain_prefix: "apps"
# Amazon key pair to use, must exist before runnign script
aws_key_pair: "gnunn"

amazon_user: "ec2-user"

# The type of OpenShift deployment, must be either origin or openshift-enterprise.
# To install OpenShift Enterprise, you must have a valid OpenShift subscription
# with Red Hat and Provide your subscription login and pool
deployment_type: "openshift-enterprise"

# Only needed for Origin
# openshift_branch: "release-1.5"

# ec2
# Use ami_id if you know the specific ami you want to use
ami_id: "ami-f05f5489"
# Use the owner tags if you want to look up the AMI automatically
#redhat_owner_id: "309956199498"
bastion_ami_size: "t2.micro"
master_ami_size: "t2.xlarge"
node_ami_size: "t2.large"
master_root_volume_size: 50
node_root_volume_size: 30
docker_volume_size: 50

app_nodes: 2

# This must match what is in /openshift-install/files/openshift_inventory.cfg
htpasswd_path: "/etc/origin/master/htpasswd"

# Users to create in OpenShift, highly recommend changing password
# Set admin to true for users you want to be the cluster administrator
users:
  - {name: admin, password: changeme!, admin: true}
  # - {name: developer1, password: changeme!, admin: false}
  # - {name: developer2, password: changeme!, admin: false}
  # - {name: developer3, password: changeme!, admin: false}
  # - {name: developer4, password: changeme!, admin: false}
  # - {name: developer5, password: changeme!, admin: false}
  # - {name: nexus, password: changeme!, admin: false}