region: "us-west-2"
availability_zone: "b"
vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"
namespace: "openshift"
# dns_zone is private zone, created and deleted by scripts
dns_zone: "ose.local"
#Public DNS for cluster
public_dns_zone: "ocplab.com"
aws_key_pair: "gnunn"
amazon_user: "ec2-user"
openshift_branch: "release-1.5"
# The type of OpenShift deployment, must be either origin or openshift-enterprise.
# To install OpenShift Enterprise, you must have a valid OpenShift subscription
# with Red Hat and Provide your subscription login and pool
deployment_type: "openshift-enterprise"

# RHSM Details
rhsm_username: ""
rhsm_password: ""
rhsm_pool: ""

# ec2
amisize: "t2.large"
amiid: "ami-f05f5489"
redhat_owner_id: "309956199498"
amazon_owner_id: "137112412989"
bastion_amisize: "t2.micro"
master_amisize: "t2.xlarge"
volume_size: 50