---

- ec2_ami_find:
     name: "RHEL-7.2*"
     owner: 309956199498
     architecture: "x86_64"
     virtualization_type: "hvm"
     sort: name
     sort_order: descending
     sort_end: 1
     region: "{{region}}"
  register: "ami_find"

- name: Provision ssh public key for access
  ec2_key:
    name: "openshift"
    key_material: "{{public_key}}"
    region: "{{region}}"
    state: "{{state}}"

- name: Provision master
  ec2:
    instance_type: "{{amisize}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "openshift"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['openshift-vpc', 'openshift-public-ingress', 'openshift-public-egress', 'openshift-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}" 
        volume_size: "{{volume_size}}"
    count_tag:
      Name: "master-{{namespace}}"
    instance_tags:
      Name: "master-{{namespace}}"
      mits4u: "{{namespace}}" 
    exact_count: 1
  register: ec2_master

- name: allocate a new elastic IP and associate it with an instance
  ec2_eip:
   device_id: "{{ec2_master['tagged_instances'][0]['id']}}"
   region: "{{region}}"
  register: master_elastic_ip

- name: Provision node1
  ec2:
    instance_type: "{{amisize}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "openshift"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['openshift-vpc', 'openshift-public-ingress', 'openshift-public-egress', 'openshift-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}"
        volume_size: "{{volume_size}}"
    count_tag:
      Name: "node1-{{namespace}}"
    instance_tags:
      Name: "node1-{{namespace}}"
      mits4u: "{{namespace}}"
    exact_count: 1
  register: ec2_node1

- name: Provision node2
  ec2:
    instance_type: "{{amisize}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "openshift"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['openshift-vpc', 'openshift-public-ingress', 'openshift-public-egress', 'openshift-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}"
        volume_size: "{{volume_size}}"
    count_tag:
      Name: "node2-{{namespace}}"
    instance_tags:
      Name: "node2-{{namespace}}"
      mits4u: "{{namespace}}"
    exact_count: 1
  register: ec2_node2
