---

  # needed for docker, see: https://forums.aws.amazon.com/thread.jspa?messageID=574126
#- name: enable repos for docker
#  shell: 'yum-config-manager --enable rhui-REGION-rhel-server-extras'
#  delegate_to: "{{item}}"
#  remote_user: "{{amazon_user}}"
#  become: true
#  register: rs
#  failed_when: "'Repository epel is listed more than once' in rs.stderr"
#  with_items: 
#   - "{{master_public_ip}}"
#   - "{{node1_public_ip}}"
#   - "{{node2_public_ip}}"

- name: install pre-req packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
      - "atomic-openshift-utils"
    state: "present"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true

- name: install pre-req packages on nodes
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker-1.12.6"
    state: "present"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items:
    - "{{master_public_ip}}"
    - "{{node1_public_ip}}"
    - "{{node2_public_ip}}"
  #register: yum_prereqs
  #async: 7200
  #poll: 0

#- debug:
#    msg: "{{ yum_prereqs }}"

#- name: Wait for yum prereqs to complete
#  async_status: jid={{ item.ansible_job_id }}"
# register: yum_jobs
#  until: yum_jobs.finished
# retries: 300
# with_items: yum_prereqs.results 

- name: Create /etc/aws folder
  file: 
   path: "/etc/aws"
   recurse: yes
   state: directory
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items:
    - "{{master_public_ip}}"
    - "{{node1_public_ip}}"
    - "{{node2_public_ip}}"

- name: upgrade all packages
  yum: name=* state=latest
  with_items: 
    - "{{bastion_public_ip}}"
    - "{{master_public_ip}}"
    - "{{node1_public_ip}}"
    - "{{node2_public_ip}}"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
#  register: yum_updates
#  async: 7200
#  poll: 0

#- name: Wait for yum updates to complete
#  async_status: jid={{ item.ansible_job_id }}
#  register: yum_jobs
#  until: yum_jobs.finished
#  retries: 300
#  with_items: yum_updates.results 

- name: Update docker options
  shell: "sed -i '/OPTIONS=.*/c\\OPTIONS=\"--selinux-enabled --insecure-registry 172.30.0.0/16\"' /etc/sysconfig/docker"  
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items: 
   - "{{master_public_ip}}"
   - "{{node1_public_ip}}"
   - "{{node2_public_ip}}"
   
- name: enable docker on master and nodes
  systemd:
     name: docker
     enabled: yes
     state: started
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items: 
   - "{{master_public_ip}}"
   - "{{node1_public_ip}}"
   - "{{node2_public_ip}}"