---

- name: install packages on bastion
  yum:
    name: "{{item}}"
    state: "present"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "ec2-user"
  with_items:
    - "git"
    - "python2-pip"
    - "openssl-devel"
    - "python-devel"
    - "gcc"
    - "libffi-devel"
    - "@Development Tools"

- name: install ansible on bastion
  pip:
    name: ansible
    version: 2.2.0.0

- name: install docker on master and nodes
  yum:
    name: "docker"
    state: "present"
  delegate_to: "{{item}}"
  remote_user: "ec2-user"
  with_items: "[{{master_public_ip}},{{node1_public_ip}},{{node2_public_ip}}]"

