---

- name: create DNS zone for openshift
  route53_zone:
     zone: "{{dns_zone}}"
     state: "{{state}}"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{region}}"
     comment: "Internal zone for Openshift"
  register: aws_zone 

- name: add master dns 
  route53:
    hosted_zone_id: "{{aws_zone['set']['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "master.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{master_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"


- name: add node1 dns 
  route53:
    hosted_zone_id: "{{aws_zone['set']['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "node1.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{node1_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"


- name: add node2 dns 
  route53:
    hosted_zone_id: "{{aws_zone['set']['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "node2.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{node2_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"

