---
- hosts: "tag_namespace_{{namespace}}"
  connection: "local"
  vars:
    region: "{{region}}"
  tasks:
  - name: terminate instance
    ec2:
      state: absent
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: localhost