---

- name: terminate instances
  hosts: "tag_namespace_{{namespace}}"
  connection: "local"
  gather_facts: false
  vars:
    region: "{{region}}"
  ec2:
    state: "absent"
    region: "{{ region }}"
    instance_ids: "{{ ec2_id }}"
    wait: true